name = "wasm-num"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["WasmNum", "WasmNumProofs"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "WasmNum"

[[lean_lib]]
name = "WasmNumProofs"

[[lean_lib]]
name = "test_api"
globs = ["test_api"]

[[lean_lib]]
name = "TestAll"
globs = ["TestAll", "WasmTest.+"]
